name: app-web lint

on:
  pull_request:
    paths:
      - 'app-web/**'
      - '.github/workflows/app-web-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'app-web/package.json'
          cache: 'npm'
          cache-dependency-path: app-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format check
        run: npm run format:check
